"""
Credential Protocol — Bundle Creator
Packages a signed credential into a sealed ZIP bundle: manifest, signature,
credential entry, a plain-text chain of evidence, and a PDF certificate.

This is a signed keepsake/backup archive, not a working access mechanism —
real access happens through the live members-page widget (personal link,
QR scan), which is the only path that respects revocation. There's no
offline verify.html in here — nobody actually verifies membership access
by unzipping a bundle and checking a signature offline, and an offline
tool couldn't check revocation anyway, so it would be maintenance weight
with no real upside.
"""

import json
import zipfile
import hashlib
import os
from pathlib import Path
from datetime import datetime, timezone
from ecdsa import SigningKey
from ecdsa.util import sigencode_der

BASE_DIR = Path(__file__).resolve().parent

# See credential_issuer.py — DATA_DIR is the persistent Volume mount in
# production, BASE_DIR as a local-dev fallback. KEYS_DIR must match where
# credential_issuer.py generates/reads the signing key — this file only
# ever reads it, never generates one.
DATA_DIR    = Path(os.environ.get("DATA_DIR", str(BASE_DIR)))
KEYS_DIR    = DATA_DIR / "keys"
BUNDLES_DIR = DATA_DIR / "bundles"
BUNDLES_DIR.mkdir(parents=True, exist_ok=True)

PRIVATE_KEY_PATH = KEYS_DIR / "credential_private.pem"


def hash_file(filepath):
    sha256 = hashlib.sha256()
    with open(filepath, "rb") as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
    return sha256.hexdigest()


def bundle_credential(issue_result: dict) -> dict:
    """
    Package a credential into a sealed ZIP bundle.
    Input: the dict returned by credential_issuer.issue_credential()
    Output: dict with bundle_path, bundle_hash, sidecar_path
    """

    credential_id = issue_result["credential_id"]
    cred_dir      = Path(issue_result["cred_dir"])
    manifest      = issue_result["manifest"]
    entry         = issue_result["entry"]

    manifest_path = cred_dir / "manifest.json"
    sig_path      = cred_dir / "manifest.sig"
    entry_path    = cred_dir / "credential_entry.json"

    # ── Generate chain of evidence txt ──
    chain_lines = [
        "CREDENTIAL PROTOCOL — CHAIN OF EVIDENCE",
        "=" * 50,
        "",
        f"Credential ID:  {credential_id}",
        f"Holder:         {manifest['holder_name']} <{manifest['holder_email']}>",
        f"Tier:           {manifest['tier']}",
        f"Sections:       {', '.join(manifest.get('sections', []))}",
        f"Issued:         {manifest['issued_at']}",
        f"Expires:        {manifest['expires_at']}",
        f"Public key:     {manifest['public_key'][:32]}...",
        "",
        "----- VERIFICATION -----",
        "STATUS: SEALED BY CREDENTIAL PROTOCOL",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "Generated by Credential Protocol",
    ]
    chain_text = "\n".join(chain_lines)
    chain_path = cred_dir / "chain_of_evidence.txt"
    with open(chain_path, "w", encoding="utf-8") as f:
        f.write(chain_text)

    # ── Generate PDF certificate ──
    pdf_path = None
    try:
        from generate_pdf_report import generate_pdf_report
        checks = {
            "seal":        True,
            "files":       True,
            "signature":   True,
            "output_hash": True,
            "merkle":      True,
            "tokens":      True,
            "anchor":      manifest["fingerprint_hash"] not in ("NOT_ANCHORED", "PENDING"),
        }
        pdf_output = cred_dir / f"{credential_id}_certificate.pdf"
        pdf_path = generate_pdf_report(
            manifest_path = manifest_path,
            proof_path    = None,
            video_path    = entry_path,
            output_path   = pdf_output,
            checks        = checks,
            bundle_name   = f"credential_{credential_id}",
            bundle_type   = "credential"
        )
    except Exception as e:
        print(f"⚠ PDF generation failed: {e}")

    # ── Create bundle ZIP ──
    # No verify.html in here — see module docstring. The bundle is a signed
    # keepsake/backup, not an offline access-verification tool.
    ts          = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    bundle_name = f"credential_{credential_id}_{ts}.zip"
    bundle_path = BUNDLES_DIR / bundle_name

    with zipfile.ZipFile(bundle_path, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(manifest_path, "manifest.json")
        z.write(sig_path,      "manifest.sig")
        z.write(entry_path,    "credential_entry.json")
        z.write(chain_path,    "chain_of_evidence.txt")
        if pdf_path and Path(pdf_path).exists():
            z.write(pdf_path, "credential_certificate.pdf")

    # ── Sign the bundle sidecar ──
    bundle_hash = hash_file(bundle_path)
    sidecar_path = Path(str(bundle_path) + ".sha256")

    try:
        with open(PRIVATE_KEY_PATH, "rb") as f:
            sk = SigningKey.from_pem(f.read())
        seal_data = json.dumps({
            "file":      bundle_name,
            "sha256":    bundle_hash,
            "sealed_at": datetime.now(timezone.utc).isoformat(),
            "sealed_by": "credential-protocol-1.0",
        }, sort_keys=True, separators=(",", ":")).encode("utf-8")
        seal_sig = sk.sign(seal_data, sigencode=sigencode_der).hex()
    except Exception:
        seal_sig = "NO_SIG"

    sidecar = {
        "file":      bundle_name,
        "sha256":    bundle_hash,
        "sealed_at": datetime.now(timezone.utc).isoformat(),
        "sealed_by": "credential-protocol-1.0",
        "signature": seal_sig,
    }
    with open(sidecar_path, "w") as f:
        json.dump(sidecar, f, indent=2)

    print(f"✔ Bundle created: {bundle_name}")
    print(f"  Hash: {bundle_hash}")
    print(f"  Sidecar: {sidecar_path.name}")

    return {
        "bundle_name":   bundle_name,
        "bundle_path":   str(bundle_path),
        "bundle_hash":   bundle_hash,
        "sidecar_path":  str(sidecar_path),
        "credential_id": credential_id,
    }


if __name__ == "__main__":
    # Test — issue a credential then bundle it
    from credential_issuer import issue_credential

    result = issue_credential(
        name        = "Test Member",
        email       = "test@example.com",
        tier        = "MEMBER",
        expiry_days = 31,
        sections    = ["downloads", "chat"],
    )

    bundle = bundle_credential(result)
    print("\nBundle result:")
    print(f"  Path: {bundle['bundle_path']}")
    print(f"  Hash: {bundle['bundle_hash']}")
